use_frameworks!

target 'SwiftAnalytics_Example' do
  pod 'SwiftAnalytics', :path => '../'

  target 'SwiftAnalytics_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
